### PR TITLE
Changed the way the project builds, updated ts-jest, added tslint to project reps and added some linting scripts

### PR DESCRIPTION
**Pull request by goooseman**
I tried to fix several issues in this PR related to the development experience of this project.

Each fix is in a separate commit, so every of them can be easily reverted if you do not need some of these changes.

The changes are:

- The transpiling of the project from .ts to .js is done on a publisher's machine before publish to npm.
- `tslint` is added to the project and `lint`/`lint:fix` scripts are created (so we will lock the tslint version we use in the project + provide an easy way for our contributors to fix the code style problems automatically)
- typescript and jest are not installed on CI globally (it will save a couple of seconds and anyway is not needed)
- `ts-jest` is updated (so you will not get a warning about mismatch with `jest` version)
- `clean` script is added to remove all generated by `tsc` files

Feel free to tell me that you do not need some of this changes, they can be easily reverted.

### About .ts transpiling on before publish hook

Right now typescript is a production dependency, so it will be installed with this library to a project, where typescript is not used. Even if typescript is installed, but the version differs, it will be installed second time in a configuration like this. 

In a Typescript world it is common to build the project to .js files on a prepublish stage and upload to npm `.js` and `.d.ts` files only in a package. 

So the lifecycle of the library is:

1. Developer works in a Typescript project as usual
1. Developer runs `npm publish`
1. Typescript compiler generates `.js` and `.d.ts` files in the project (to compile `.d.ts` files `declaration: true` was added to `tsconfig.json` in the root of the project)
1. npm uploads only `.js` and `d.ts` files to npm (that is why we need `files` section in `package.json`)
1. If the project is added to JS project, `typescript` is not installed.
1. If the project is added to TS project, `typescript` is not installed, and `.d.ts` files from the package are used to get type definitions of the project.

### CODE REVIEW

**Comment by goooseman** [comment]
What else I propose to do:

- Add [husky](https://github.com/typicode/husky), so we can run lint script on each commit. This way contributor will never commit something, that will not pass the code style check
- Add [prettier](https://github.com/prettier/prettier), and we can run it for every commit with `husky`. This way you will receive cleaner diffs from your contributors, because all the code will be formatted in absolutely the same way
- Add [lint-staged](https://github.com/okonet/lint-staged), so we can run prettier only in the changed files of the project. Can be kinda useless, because the size of the project allows us to pretty all the project each commit without any serious waiting time

I can added these tools, but I need your approval to do such serious changes as adding some new tools.

**Comment by goooseman** [comment]
What has been changed:

- `husky` is installed, so `tslint` run on each commit
- `prettier` is installed and configured to match an existing code style of the project
- `prettier` is ran across all the project to make code style consistent
- `lint-staged` is installed and configured to run `prettier` and `tslint --fix` on all changed files

I did not want to install `lint-staged` first, because I thought there is no need.
But then I faced with the following problem: if prettier is run on each commit, we need to add these changes files to git. I do not want to do `git add -A` on each commit because it will cause a lot of side-effects (developer can add to stage only a part of a project), so a way to `git add` only changed by prettier files was needed.

The easiest way to do this was to install `lint-staged`. It runs `prettier` and `tslint` on all changed files and adds them to git stage on every commit.

**Comment by goooseman** [comment]
Codacy does not work for some reason. Could not investigate why.

**Comment by ScriptSmith** [comment]
Looks good. If there are no further changes, I will merge.

**Pull request merged**
